---
- op: add
  path: "/spec/template/spec/containers/1"
  value:
    args:
    - "-envoy.port=15020"
    - "-container=minio-mc"
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: paskalmaksim/envoy-sidecar-helper:latest
    imagePullPolicy: Always
    name: envoy-sidecar-helper
    resources:
      limits:
        cpu: 200m
        ephemeral-storage: 1Mi
        memory: 20Mi
      requests:
        cpu: 200m
        ephemeral-storage: 1Mi
        memory: 20Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      privileged: false
      readOnlyRootFilesystem: true
