---
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - values.yaml
  name: harbor-s3-overrides
  namespace: flux-system
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- minio.yaml
- namespace.yaml
- release.yaml
