---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-s3
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: datasource=helm registryUrl=https://charts.min.io/
      chart: minio
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: 4.0.15
  install:
    remediation:
      retries: -1
  interval: 15m
  postRenderers:
  - kustomize:
      patchesJson6902:
      - patch:
        - op: add
          path: "/spec/template/spec/containers/1"
          value:
            args:
            - "-envoy.port=15020"
            - "-container=minio-mc"
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            image: paskalmaksim/envoy-sidecar-helper:latest
            imagePullPolicy: Always
            name: envoy-sidecar-helper
            resources:
              limits:
                cpu: 200m
                ephemeral-storage: 1Mi
                memory: 20Mi
              requests:
                cpu: 200m
                ephemeral-storage: 1Mi
                memory: 20Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - all
              privileged: false
              readOnlyRootFilesystem: true
        target:
          group: batch
          kind: Job
          name: harbor-s3-minio-make-user-job
          version: v1
  releaseName: harbor-s3
  targetNamespace: harbor
  timeout: 15m
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: harbor-s3-overrides
  - kind: ConfigMap
    name: harbor-s3-additional-overrides
    optional: true
